[package]
name = "bevy_extensions"
version = "0.1.2"
authors = ["SecretPocketCat <jiridexterhanc@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }

[dev-dependencies]
pretty_assertions = "1.0.0"
