[package]
name = "bevy_extensions"
version = "0.1.3"
authors = ["SecretPocketCat <jiridexterhanc@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.6.1", default-features = false }

[dev-dependencies]
pretty_assertions = "1.0.0"
